# Generated by Django 5.0 on 2025-09-24 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='job',
            name='company_logo',
            field=models.URLField(blank=True, help_text='URL to company logo image'),
        ),
        migrations.AddField(
            model_name='job',
            name='company_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='job',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude coordinate', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude coordinate', null=True),
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('reviewed', 'Under Review'), ('interview', 'Interview Scheduled'), ('rejected', 'Rejected'), ('accepted', 'Accepted')], default='applied', max_length=20)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-applied_at'],
                'unique_together': {('job', 'user')},
            },
        ),
    ]
