# Generated by Django 5.0 on 2025-09-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_alter_job_options_job_company_logo_job_company_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="note",
            field=models.TextField(
                blank=True, help_text="Optional note from the applicant"
            ),
        ),
    ]
