# Generated by Django 5.0 on 2025-10-24 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobapplication_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('color', models.CharField(default='#007bff', help_text='Hex color code', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moved_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this stage')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline', to='jobs.jobapplication')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.pipelinestage')),
            ],
            options={
                'ordering': ['-moved_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('skills', models.TextField(blank=True, help_text='Comma-separated skills to search for')),
                ('location', models.CharField(blank=True, max_length=120)),
                ('location_radius', models.PositiveIntegerField(default=50, help_text='Radius in kilometers')),
                ('education_keywords', models.TextField(blank=True, help_text='Education keywords to search for')),
                ('experience_keywords', models.TextField(blank=True, help_text='Experience keywords to search for')),
                ('notify_on_new_matches', models.BooleanField(default=True)),
                ('last_notified', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_notifications', to=settings.AUTH_USER_MODEL)),
                ('saved_search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='jobs.savedsearch')),
            ],
            options={
                'ordering': ['-sent_at'],
                'unique_together': {('saved_search', 'candidate')},
            },
        ),
    ]
