# Generated by Django 5.0 on 2025-09-24 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline", models.CharField(blank=True, max_length=120)),
                ("skills", models.TextField(blank=True)),
                ("education", models.TextField(blank=True)),
                ("experience", models.TextField(blank=True)),
                ("links", models.TextField(blank=True)),
                ("is_public", models.BooleanField(default=True)),
                ("commute_radius_km", models.PositiveIntegerField(default=10)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
