# Generated by Django 5.0 on 2025-10-23 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile_show_education_profile_show_experience_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="user_type",
            field=models.CharField(
                choices=[("job_seeker", "Job Seeker"), ("recruiter", "Recruiter")],
                default="job_seeker",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="RecruiterProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("company_description", models.TextField(blank=True)),
                ("company_website", models.URLField(blank=True)),
                ("company_logo", models.URLField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                ("industry", models.CharField(blank=True, max_length=100)),
                ("company_size", models.CharField(blank=True, max_length=50)),
                ("is_verified", models.BooleanField(default=False)),
                ("verification_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recruiter_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
