# Generated by Django 5.0 on 2025-11-24 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_profile_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "school_name",
                    models.CharField(
                        help_text="University or school name", max_length=200
                    ),
                ),
                (
                    "degree",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Bachelor of Science, Master's",
                        max_length=100,
                    ),
                ),
                (
                    "field_of_study",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Computer Science, Business",
                        max_length=100,
                    ),
                ),
                (
                    "gpa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="e.g., 3.75",
                        max_digits=3,
                        null=True,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Leave blank if currently enrolled",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Activities, honors, coursework, etc."
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order (0 = most recent)"
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education_entries",
                        to="accounts.profile",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Education entries",
                "ordering": ["order", "-end_date"],
            },
        ),
        migrations.CreateModel(
            name="WorkExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_title",
                    models.CharField(
                        help_text="e.g., Software Engineer, Product Manager",
                        max_length=150,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        help_text="Company or organization name", max_length=200
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, help_text="City, State", max_length=100
                    ),
                ),
                (
                    "start_date",
                    models.DateField(help_text="When you started this role"),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Leave blank if current position",
                        null=True,
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=False, help_text="Check if this is your current role"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Key responsibilities and achievements"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order (0 = most recent)"
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_experiences",
                        to="accounts.profile",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Work experiences",
                "ordering": ["order", "-start_date"],
            },
        ),
    ]
